---
title: Movebank Results
output: 
  github_document:
    df_print: kable
author: Alec Robitaille
date: "`r Sys.Date()`"
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

knitr::opts_chunk$set(echo = TRUE,
											eval = TRUE)
```




```{r pkgs}
# Packages ----------------------------------------------------------------
library(data.table)
library(taxize)
library(ggplot2)
```

```{r data}
# Data --------------------------------------------------------------------
details <- fread('data-sources/details.csv')
taxes <- fread('data-sources/taxes.csv')
DT <- fread('data-sources/taxed-details.csv')
```


`taxon_ids` column

```{r checkids}
details[, .N, .(is.na(taxon_ids), taxon_ids == '')]
```


Out of `r details[taxon_ids == '', .N]` rows with seemingly valid `taxon_ids`, there are up to 17 species listed in any row. Eg. 


```{r eglong}
details[id == 422952928]$taxon_ids
```

Grabbing the family and class, then combining the taxonomies with the study details dataset, we have `r DT[, .N]` species by study rows. 


TODO: N access, family, class, access by taxonomy etc

```{r class}
DT[, .N, class]

ggplot(DT) + 
	geom_bar(aes(class, fill = factor(i_have_download_access)))
```

```{r studies, fig.height=9}
ggplot(DT[class == 'Mammalia']) + 
	geom_bar(aes(factor(family, sort(unique(family), TRUE)),
							 fill = factor(i_have_download_access))) +
	coord_flip() +
	labs(y = 'Number of studies', x = 'Family')
```


```{r numbids, fig.height=9}
ggplot(DT[class == 'Mammalia', sum(number_of_individuals), .(i_have_download_access, family)]) + 
	geom_col(aes(factor(family, sort(unique(family), TRUE)),
							 V1,
							 fill = factor(i_have_download_access))) +
	coord_flip() +
	labs(y = 'Number of individuals', x = 'Family')
```

```{r numblobs, fig.height=9}
ggplot(DT[class == 'Mammalia', sum(number_of_deployed_locations), .(i_have_download_access, family)]) + 
	geom_col(aes(factor(family, sort(unique(family), TRUE)),
							 V1,
							 fill = factor(i_have_download_access))) +
	coord_flip() +
	labs(y = 'Number of relocations', x = 'Family')
```
